
    <ul class="nav navbar-nav">
        <?php foreach ($this->container as $page):
            /** @var Zend\Navigation\Page\AbstractPage $page */ ?>
            <li class="<?php echo ($page->hasPages() && $this->zfcUserIdentity()) ? 'dropdown' : '' ?>">
                <a href="<?php echo $page->getHref() ?>" target="<?php echo $page->getTarget() ?>"
                    <?php echo ($page->hasPages() && $this->zfcUserIdentity()) ? 'class="dropdown-toggle" data-toggle="dropdown"' : '' ?>>
                    <?php echo $page->getLabel() ?>
                    <?php if ($page->hasPages() && $this->zfcUserIdentity()): ?>
                        <span class="caret"></span>
                    <?php endif; ?>
                </a>
                <?php if ($page->hasPages() && $this->zfcUserIdentity()): ?>
                    <ul class="dropdown-menu">
                        <?php foreach ($page->getPages() as $child):
                            /** @var Zend\Navigation\Page\AbstractPage $child */ ?>
                            <li>
                                <a href="<?php echo $child->getHref() ?>">
                                    <?php echo $child->getLabel() ?>
                                </a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>

